### PR TITLE
CMake: Find HDF5 Version

### PR DESCRIPTION
**Pull request by ax3l**
The default `FindHDF5.cmake` module has no VERSION support.

The introduced "requirement" in #169 is without effect for now - this pull request changes that.

An upstream patch was send to: https://github.com/Kitware/CMake/pull/153, now [in review](http://public.kitware.com/pipermail/cmake-developers/2015-May/025225.html) -> [merged](https://github.com/Kitware/CMake/commit/58d6709e64d3ae061da2b9db49ce9d884a77e654)!

Available since 25th of July 2015 in [CMake 3.3.0+](http://www.kitware.com/blog/home/post/940) (but not announced in the blog post ;) )

### CODE REVIEW

**Comment by ax3l** [comment]
still [under external review](http://public.kitware.com/pipermail/cmake-developers/2015-May/025225.html).

let's see what others think before we merge a pre-mature version :)

**Comment by ax3l** [comment]
merged upstream! :) https://github.com/Kitware/CMake/commit/58d6709e64d3ae061da2b9db49ce9d884a77e654

until the cmake version that will ship that updated module is mature, we should merge and use the version in this pull.

**Comment by psychocoderHPC** [comment]
:+1:

**Comment by ax3l** [comment]
@f-schmitt-zih pls merge me :)

**Comment by ax3l** [comment]
@f-schmitt-zih we have two options now: either you merge this fantastic pull request or I will increase the CMake requirement to `3.3.0` using the 5 days old release of CMake ;)

just kidding, pls merge.

**Pull request merged**
